/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database_project2;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author SARK
 */
public class EmployeeDetails extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeDetails
     */
    EmployeeInfo user;
    ArrayList<EmployeeInfo> arr = new ArrayList ();
    String AdminId,EmployeeId;
    
    public EmployeeDetails() {
        initComponents();
    }
    
    public EmployeeDetails(String AdminId,String EmployeeId) 
    {
        
        this.AdminId = AdminId;
        this.EmployeeId = EmployeeId;
        initComponents();
        System.out.println(this.AdminId+" "+this.EmployeeId);
        arr = new ConnectMSSQL().getEmployeeInfo("where EmployeeId = "+EmployeeId);
        //System.out.println(arr.size());
        user = arr.get(0);
        name.setText(user.getName());
        fathersName.setText(user.getFathersName());
        mothersName.setText(user.getMothersName());
        email.setText(user.getEmail());
        contactNo.setText(user.getContactNo());
        bloodGroup.setText(user.getContactNo());
        dateOfBirth.setText(user.getDateOfBirth());
        bloodGroup.setText(user.getBloodGroup());
        post.setText(user.getPost());
        gContactNo.setText(user.getGuardianContactNo());
        address.setText(user.getAddress());  
        salary.setText(Integer.toString(user.getSalary()));
  
        InputStream in = new ByteArrayInputStream(user.getImage());
        BufferedImage img = null;
        try
        {
            img = ImageIO.read(in);  
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
                 
        Image dimg = img.getScaledInstance(image.getWidth(), image.getHeight(),Image.SCALE_SMOOTH);
        Icon icon = new ImageIcon(dimg);
        image.setIcon(icon);
    }

    

    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        fathersName = new javax.swing.JTextField();
        mothersName = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        bloodGroup = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        salary = new javax.swing.JTextField();
        contactNo = new javax.swing.JTextField();
        post = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        gContactNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1050, 570));
        setMinimumSize(new java.awt.Dimension(1050, 570));
        setPreferredSize(new java.awt.Dimension(1050, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 19, 52));

        jLabel1.setText("Employee Information");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(backButton)
                .addGap(357, 357, 357)
                .addComponent(jLabel1)
                .addContainerGap(486, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(jLabel1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Contact No:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Mother's Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 60, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Salary:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 80, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Post:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Date of Birth:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Blood Group:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Guardian Contact No:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Father's Name:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 140, 30));

        name.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        name.setEnabled(false);
        name.setPreferredSize(new java.awt.Dimension(59, 27));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 190, 30));

        fathersName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fathersName.setEnabled(false);
        fathersName.setPreferredSize(new java.awt.Dimension(59, 27));
        getContentPane().add(fathersName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 190, 30));

        mothersName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mothersName.setEnabled(false);
        mothersName.setPreferredSize(new java.awt.Dimension(59, 27));
        mothersName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothersNameActionPerformed(evt);
            }
        });
        getContentPane().add(mothersName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 190, 30));

        email.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        email.setEnabled(false);
        email.setPreferredSize(new java.awt.Dimension(59, 27));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 190, 30));

        bloodGroup.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        bloodGroup.setEnabled(false);
        bloodGroup.setPreferredSize(new java.awt.Dimension(59, 27));
        getContentPane().add(bloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 190, 30));

        address.setColumns(20);
        address.setRows(5);
        address.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        address.setEnabled(false);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 190, 60));

        salary.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        salary.setEnabled(false);
        salary.setPreferredSize(new java.awt.Dimension(59, 27));
        getContentPane().add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 190, 30));

        contactNo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        contactNo.setEnabled(false);
        contactNo.setPreferredSize(new java.awt.Dimension(59, 27));
        getContentPane().add(contactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 190, 30));

        post.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        post.setEnabled(false);
        post.setPreferredSize(new java.awt.Dimension(59, 27));
        getContentPane().add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 190, 30));

        dateOfBirth.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        dateOfBirth.setEnabled(false);
        dateOfBirth.setPreferredSize(new java.awt.Dimension(59, 27));
        getContentPane().add(dateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 190, 30));

        image.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 120, 120));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Name:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 92, -1, 30));

        gContactNo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        gContactNo.setEnabled(false);
        gContactNo.setPreferredSize(new java.awt.Dimension(59, 27));
        getContentPane().add(gContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 190, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Address:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 90, 20));

        jPanel2.setBackground(new java.awt.Color(70, 130, 180));

        deleteButton.setText("Delete");
        deleteButton.setBackground(new java.awt.Color(255, 0, 0));
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.setBackground(new java.awt.Color(51, 51, 255));
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(404, Short.MAX_VALUE)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(422, 422, 422))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(418, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(editButton))
                .addGap(57, 57, 57))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1050, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new Employee(this.AdminId).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void mothersNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothersNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothersNameActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        new EmployeeEdit(user,AdminId).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int query = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete?","Confirm", JOptionPane.OK_CANCEL_OPTION);
        if(query==0)
        {
            try
            {
                new ConnectMSSQL().delete("Employee", "where EmployeeId = '"+user.getEmployeeId()+"'");
                new Employee(AdminId).setVisible(true);
                this.setVisible(false);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error Occured","Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField bloodGroup;
    private javax.swing.JTextField contactNo;
    private javax.swing.JTextField dateOfBirth;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fathersName;
    private javax.swing.JTextField gContactNo;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mothersName;
    private javax.swing.JTextField name;
    private javax.swing.JTextField post;
    private javax.swing.JTextField salary;
    // End of variables declaration//GEN-END:variables
}
