/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tanjim
 */
package database_project2;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

public class Payment extends javax.swing.JFrame {
    String AdminId;
    String str = new String();
    ArrayList<MemberInfo> ar = new ArrayList();
    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }
    
    public Payment(String AdminId)
    {
        this.AdminId = AdminId;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        due = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        memberId = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        paymentHistoryButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1050, 570));
        setMinimumSize(new java.awt.Dimension(1050, 570));
        setPreferredSize(new java.awt.Dimension(1050, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 19, 52));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payment");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(backButton)
                .addGap(344, 344, 344)
                .addComponent(jLabel1)
                .addContainerGap(526, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Amount:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 100, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Due:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 100, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Member Id:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, 30));

        due.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        due.setEnabled(false);
        getContentPane().add(due, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 300, 40));

        name.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        name.setEnabled(false);
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 300, 40));

        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountKeyTyped(evt);
            }
        });
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 300, 40));

        memberId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                memberIdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                memberIdKeyTyped(evt);
            }
        });
        getContentPane().add(memberId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 300, 40));

        resetButton.setBackground(new java.awt.Color(255, 51, 0));
        resetButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 80, 30));

        submitButton.setBackground(new java.awt.Color(15, 19, 52));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 80, 30));

        paymentHistoryButton.setBackground(new java.awt.Color(15, 19, 52));
        paymentHistoryButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paymentHistoryButton.setForeground(new java.awt.Color(255, 255, 255));
        paymentHistoryButton.setText("Payment History");
        paymentHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentHistoryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(paymentHistoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 140, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1050, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void memberIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memberIdKeyTyped
        char ch = evt.getKeyChar();
        if(!((ch>='0' && ch<='9')|| ch==KeyEvent.VK_BACK_SPACE ))
        {
            evt.consume();
        }
                
        
    }//GEN-LAST:event_memberIdKeyTyped

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new HomePage(this.AdminId).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void paymentHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentHistoryButtonActionPerformed
        new PaymentHistory(this.AdminId).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_paymentHistoryButtonActionPerformed

    private void memberIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memberIdKeyPressed
        char ch  = evt.getKeyChar();
        if(!((ch>='0' && ch<='9') || ch==KeyEvent.VK_BACK_SPACE   ))
        {
            evt.consume();
        }
        else
        {
            if(ch!=KeyEvent.VK_BACK_SPACE )
                str+= ch;
            else
            {
                if(str.length()!=0)
                {
                    str =  str.substring(0, str.length()-1);
                }
            }
            
            System.out.println(str);
            
            ar.clear();
            ar = new ConnectMSSQL().getMemberInfo("where MemberId =  '"+str+"'");
            if(ar.size()==0)
            {
                name.setText("MemberId Does Not Exist");
                due.setText("");
            }
            else
            {
                name.setText(ar.get(0).getName());
                due.setText(Integer.toString(ar.get(0).getDue()));
            }
            
        }
        
    }//GEN-LAST:event_memberIdKeyPressed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        str  ="";
        memberId.setText("");
        name.setText("");
        due.setText("");
        amount.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if(due.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Member Id is not valid","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(amount.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Amount is Empty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(amount.getText().length()>7)
        {
            JOptionPane.showMessageDialog(this, "Amount size should be less than or equal to 7 digits","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            PaymentInfo pay = new PaymentInfo();
            pay.setMemberId(memberId.getText());
            pay.setName(name.getText());
            pay.setAmount(Integer.parseInt(amount.getText()));
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");  
            Date date = new Date();  
            String f = formatter.format(date);  
            pay.setDateAndTime(f);
            pay.setPaymentId(f.substring(0,4)+f.substring(5,7)+f.substring(8,10)+f.substring(11,13)+f.substring(14,16)+f.substring(17,19)+new ConnectMSSQL().getSerial("PaymentSerial"));
            pay.setAdminId(this.AdminId);
            System.out.println(pay.getPaymentId());
            try
            {
                new ConnectMSSQL().addPayment(pay);
                
                new ConnectMSSQL().update("SerialNo", "PaymentSerial = PaymentSerial+1");
                ArrayList<MemberInfo> arr = new ConnectMSSQL().getMemberInfo("where MemberId = "+memberId.getText());
                //System.out.println(arr.size());
                MemberInfo user = arr.get(0);
                user.setDue(user.getDue()-pay.getAmount());
                new ConnectMSSQL().updateMember(user);
                JOptionPane.showMessageDialog(this, "Payment Successful","Succesful",JOptionPane.INFORMATION_MESSAGE);
                resetButtonActionPerformed(evt);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error Occured,Payment Unsuccessful","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
            
    }//GEN-LAST:event_submitButtonActionPerformed

    private void amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyTyped
       char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
        }
        
    }//GEN-LAST:event_amountKeyTyped

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField due;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField memberId;
    private javax.swing.JTextField name;
    private javax.swing.JButton paymentHistoryButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
