/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database_project2;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javafx.util.Pair;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author SARK
 */
public class AccessControl extends javax.swing.JInternalFrame {

    /**
     * Creates new form AccessControl
     */
    AdminInfo admin =  new AdminInfo();
    ArrayList<AdminInfo> arr = new ArrayList();
    public AccessControl() {
        initComponents();
        
        arr = new ConnectMSSQL().getAdminInfo("");
        for(int i=0;i<arr.size();i++)
        {
            jTable1.getModel().setValueAt(arr.get(i).getEmployeeId(),i, 0);
            jTable1.getModel().setValueAt(arr.get(i).getUserName(),i, 1);
            jTable1.getModel().setValueAt(arr.get(i).getAdminType(),i, 2);
            jTable1.getModel().setValueAt("Remove", i,3);
                
            
            
             
        }
        
        jTable1.getColumn("Action").setCellRenderer(new ButtonRenderer(arr.size()));
        jTable1.getColumn("Action").setCellEditor(new ButtonEditor(new JCheckBox(),jTable1));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        employeeId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        adminType = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(750, 570));
        setMinimumSize(new java.awt.Dimension(750, 570));
        setPreferredSize(new java.awt.Dimension(750, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 19, 52));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Access Control");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 734, 50));

        username.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        username.setPreferredSize(new java.awt.Dimension(59, 27));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 145, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("UserName:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 91, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Password:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 91, -1));

        password.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        password.setPreferredSize(new java.awt.Dimension(59, 27));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 145, -1));

        employeeId.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        employeeId.setPreferredSize(new java.awt.Dimension(59, 27));
        employeeId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                employeeIdKeyTyped(evt);
            }
        });
        getContentPane().add(employeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 145, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Employee Id:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 100, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Admin Type:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 91, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee Id", "User Name", "AdminType", "Action"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 660, 160));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Admin/Moderator List");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 220, 30));

        submitButton.setBackground(new java.awt.Color(15, 19, 52));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Add Admin/Moderator");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 220, 30));

        adminType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Moderator" }));
        getContentPane().add(adminType, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        char c = evt.getKeyChar();
        if (!(((c >= '0') && (c <= '9'))  || ((c >= 'a') && (c <= 'z'))  ||
            (c == KeyEvent.VK_BACK_SPACE) ||
            (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_usernameKeyTyped

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        char c = evt.getKeyChar();
        if (!(((c >= '0') && (c <= '9'))  || ((c >= 'a') && (c <= 'z'))  ||
            (c == KeyEvent.VK_BACK_SPACE) ||
            (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_passwordKeyTyped

    private void employeeIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeIdKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
            (c == KeyEvent.VK_BACK_SPACE) ||
            (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_employeeIdKeyTyped
     public static void clearTable(final JTable table) 
    {
        for (int i = 0; i < table.getRowCount(); i++) 
        {
            for(int j = 0; j < table.getColumnCount(); j++) 
            {
                table.setValueAt("", i, j);
            }   
        }
    }
     
     
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if(username.getText().length()<6)
        {
            JOptionPane.showMessageDialog(this, "Username should be at least 6 charcaters","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(password.getText().length()<6)
        {
            JOptionPane.showMessageDialog(this, "Password should be at least 6 charcaters","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            ArrayList<EmployeeInfo> arr3  = new ArrayList();
            arr3 = new ConnectMSSQL().getEmployeeInfo("where EmployeeId = '"+employeeId.getText()+"'");
            if(arr3.size()==0)
            {
                JOptionPane.showMessageDialog(this, "Employee Id is Invalid","Error",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                ArrayList<AdminInfo> arr2  = new ConnectMSSQL().getAdminInfo("where username = '"+username.getText()+"'");
                if(arr2.size()>0)
                {
                    JOptionPane.showMessageDialog(this, "Username Already Exist!","Error",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    try
                    {
                        admin.setUserName(username.getText());
                        admin.setPassword(password.getText());
                        admin.setEmployeeId(employeeId.getText());
                        admin.setAdminType(adminType.getSelectedItem().toString());
                        new ConnectMSSQL().addAdmin(admin);
                        JOptionPane.showMessageDialog(this, "Added Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
                        clearTable(jTable1);
                        arr = new ConnectMSSQL().getAdminInfo("");
                        for(int i=0;i<arr.size();i++)
                        {
                            jTable1.getModel().setValueAt(arr.get(i).getEmployeeId(),i, 0);
                            jTable1.getModel().setValueAt(arr.get(i).getUserName(),i, 1);
                            jTable1.getModel().setValueAt(arr.get(i).getAdminType(),i, 2);
                            jTable1.getModel().setValueAt("Remove", i,3);




                        }

                        jTable1.getColumn("Action").setCellRenderer(new ButtonRenderer(arr.size()));
                        jTable1.getColumn("Action").setCellEditor(new ButtonEditor(new JCheckBox(),jTable1));
                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this, "Error Occured","Error",JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
            
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();
        
        if(col==3 && row<arr.size())
        {
            int x = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove?", "Confirm", JOptionPane.OK_CANCEL_OPTION);
            if(x==0)
            {
                ArrayList<AdminInfo> temp = new ConnectMSSQL().getAdminInfo("where adminType = 'Admin'");
                if(temp.size()==1 && arr.get(row).getAdminType().equals("Admin"))
                {
                    JOptionPane.showMessageDialog(this, "At least one admin is needed", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    
                    try
                    {
                        new ConnectMSSQL().delete("Admin"," where EmployeeId = '"+jTable1.getValueAt(row, 0)+"'");
                        JOptionPane.showMessageDialog(this, "Removed Succesfully", "Success", JOptionPane.INFORMATION_MESSAGE);

                        clearTable(jTable1);
                        arr = new ConnectMSSQL().getAdminInfo("");
                        for(int i=0;i<arr.size();i++)
                        {
                            jTable1.getModel().setValueAt(arr.get(i).getEmployeeId(),i, 0);
                            jTable1.getModel().setValueAt(arr.get(i).getUserName(),i, 1);
                            jTable1.getModel().setValueAt(arr.get(i).getAdminType(),i, 2);
                            jTable1.getModel().setValueAt("Remove", i,3);




                        }

                        jTable1.getColumn("Action").setCellRenderer(new ButtonRenderer(arr.size()));
                        jTable1.getColumn("Action").setCellEditor(new ButtonEditor(new JCheckBox(),jTable1));
                            
                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this, "Error Occured", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adminType;
    private javax.swing.JTextField employeeId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField password;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
